services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: judicial_db
      POSTGRES_USER: judicial
      POSTGRES_PASSWORD: judicial123
    ports:
      - "5433:5432"  # Cambia aqu√≠ el puerto externo
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage