services:
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: judicial_db
  #     POSTGRES_USER: judicial
  #     POSTGRES_PASSWORD: xdLhH0k3t3b2
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  # backend:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./uploaded_docs:/app/uploaded_docs
  #   depends_on:
  #     - postgres
  #     - qdrant